const recipes = require('./src/data/recipes.json');

const regionTranslations = {
  'Adygey': 'Адыгея',
  'Altay': 'Алтай', 
  'Amur': 'Амурская область',
  'Arkhangel\'sk': 'Архангельская область',
  'Astrakhan\'': 'Астраханская область',
  'Bashkortostan': 'Башкортостан',
  'Belgorod': 'Белгородская область',
  'Bryansk': 'Брянская область',
  'Buryat': 'Бурятия',
  'Chechnya': 'Чечня',
  'Chelyabinsk': 'Челябинская область',
  'Chukot': 'Чукотский АО',
  'Chukchi Autonomous Okrug': 'Чукотский АО',
  'Chuvash': 'Чувашия',
  'City of St. Petersburg': 'Санкт-Петербург',
  'Crimea': 'Крым',
  'Dagestan': 'Дагестан',
  'Gorno-Altay': 'Республика Алтай',
  'Ingush': 'Ингушетия',
  'Irkutsk': 'Иркутская область',
  'Ivanovo': 'Ивановская область',
  'Kabardin-Balkar': 'Кабардино-Балкария',
  'Kaliningrad': 'Калининградская область',
  'Kalmyk': 'Калмыкия',
  'Kaluga': 'Калужская область',
  'Kamchatka': 'Камчатский край',
  'Karachay-Cherkess': 'Карачаево-Черкесия',
  'Karelia': 'Карелия',
  'Kemerovo': 'Кемеровская область',
  'Khabarovsk': 'Хабаровский край',
  'Khakass': 'Хакасия',
  'Khanty-Mansiy': 'Ханты-Мансийский АО',
  'Kirov': 'Кировская область',
  'Komi': 'Коми',
  'Kostroma': 'Костромская область',
  'Krasnodar': 'Краснодарский край',
  'Krasnoyarsk': 'Красноярский край',
  'Kurgan': 'Курганская область',
  'Kursk': 'Курская область',
  'Leningrad': 'Ленинградская область',
  'Lipetsk': 'Липецкая область',
  'Magadan': 'Магаданская область',
  'Maga Buryatdan': 'Магаданская область',
  'Mariy-El': 'Марий Эл',
  'Mordovia': 'Мордовия',
  'Moscow City': 'Москва',
  'Moskva': 'Московская область',
  'Murmansk': 'Мурманская область',
  'Nenets': 'Ненецкий АО',
  'Nizhegorod': 'Нижегородская область',
  'North Ossetia': 'Северная Осетия',
  'Novgorod': 'Новгородская область',
  'Novosibirsk': 'Новосибирская область',
  'Omsk': 'Омская область',
  'Orel': 'Орловская область',
  'Orenburg': 'Оренбургская область',
  'Penza': 'Пензенская область',
  'Perm\'': 'Пермский край',
  'Primor\'ye': 'Приморский край',
  'Pskov': 'Псковская область',
  'Rostov': 'Ростовская область',
  'Ryazan\'': 'Рязанская область',
  'Sakha': 'Якутия',
  'Sakha (Yakutia)': 'Якутия',
  'Sakhalin': 'Сахалинская область',
  'Samara': 'Самарская область',
  'Saratov': 'Саратовская область',
  'Sevastopol\'': 'Севастополь',
  'Smolensk': 'Смоленская область',
  'Stavropol\'': 'Ставропольский край',
  'Sverdlovsk': 'Свердловская область',
  'Tambov': 'Тамбовская область',
  'Tatarstan': 'Татарстан',
  'Tomsk': 'Томская область',
  'Tula': 'Тульская область',
  'Tuva': 'Тыва',
  'Tver\'': 'Тверская область',
  'Tyumen\'': 'Тюменская область',
  'Udmurt': 'Удмуртия',
  'Ul\'yanovsk': 'Ульяновская область',
  'Vladimir': 'Владимирская область',
  'Volgograd': 'Волгоградская область',
  'Vologda': 'Вологодская область',
  'Voronezh': 'Воронежская область',
  'Yamal-Nenets': 'Ямало-Ненецкий АО',
  'Yaroslavl\'': 'Ярославская область',
  'Yevrey': 'Еврейская АО',
  'Zabaykal\'ye': 'Забайкальский край',
  'Zabaikalskiy Krai': 'Забайкальский край',
  'Chita': 'Забайкальский край'
};

const regionsWithRecipes = new Set(Object.keys(recipes.regions));
const allRegions = new Set(Object.values(regionTranslations));
const regionsWithoutRecipes = [...allRegions].filter(region => !regionsWithRecipes.has(region));

console.log('Регионы без рецептов:');
regionsWithoutRecipes.sort().forEach((region, index) => {
  console.log(`${index + 1}. ${region}`);
});
console.log(`\nВсего регионов без рецептов: ${regionsWithoutRecipes.length}`);
console.log(`Всего регионов с рецептами: ${regionsWithRecipes.size}`);
console.log(`Общее количество регионов: ${allRegions.size}`); 